# Generated by Django 6.0.5 on 2026-05-23 09:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('subject', models.TextField()),
                ('details', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_edited', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['-creation_date'],
            },
        ),
    ]
