# Generated by Django 6.0.6 on 2026-08-07 20:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name_snapshot', models.CharField(blank=True, max_length=250)),
                ('user_email_snapshot', models.CharField(blank=True, max_length=320)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('subject', models.TextField()),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('new', 'جديد'), ('in_progress', 'قيد المعالجة'), ('completed', 'مكتمل'), ('rejected_spam', 'مرفوض / مزعج')], db_index=True, default='new', max_length=20)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_edited', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['-creation_date'],
            },
        ),
    ]
