# Generated by Django 6.0.6 on 2026-08-07 20:25

import catalog.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(db_index=True, max_length=200, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(blank=True, default='', max_length=200, verbose_name='الاسم (إنجليزي)')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='المعرف')),
                ('image', models.ImageField(upload_to='categories/', verbose_name='الصورة الرئيسية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'db_table': 'categories',
                'ordering': ['display_order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sar_to_yer_rate', models.DecimalField(decimal_places=2, default=410, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='سعر صرف الريال مقابل الريال اليمني')),
                ('local_phone', models.CharField(default='783278181', max_length=30, verbose_name='رقم الجوال المحلي')),
                ('whatsapp_number', models.CharField(default='967783278181', max_length=30, verbose_name='رقم واتساب دولي')),
                ('address_ar', models.TextField(blank=True, default='', verbose_name='العنوان (عربي)')),
                ('address_en', models.TextField(blank=True, default='', verbose_name='العنوان (إنجليزي)')),
                ('light_color_primary', models.CharField(default='#30669c', max_length=7, validators=[catalog.models._validate_hex_color], verbose_name='اللون الأساسي (فاتح)')),
                ('light_color_secondary', models.CharField(default='#08121b', max_length=7, validators=[catalog.models._validate_hex_color], verbose_name='اللون الثانوي (فاتح)')),
                ('light_color_accent', models.CharField(default='#e0801f', max_length=7, validators=[catalog.models._validate_hex_color], verbose_name='لون التمييز (فاتح)')),
                ('light_color_background', models.CharField(default='#f6f1ee', max_length=7, validators=[catalog.models._validate_hex_color], verbose_name='لون الخلفية (فاتح)')),
                ('light_color_surface', models.CharField(default='#ffffff', max_length=7, validators=[catalog.models._validate_hex_color], verbose_name='لون السطح (فاتح)')),
                ('dark_color_primary', models.CharField(default='#39f2f9', max_length=7, validators=[catalog.models._validate_hex_color], verbose_name='اللون الأساسي (داكن)')),
                ('dark_color_secondary', models.CharField(default='#e0ebe7', max_length=7, validators=[catalog.models._validate_hex_color], verbose_name='اللون الثانوي (داكن)')),
                ('dark_color_accent', models.CharField(default='#e7994b', max_length=7, validators=[catalog.models._validate_hex_color], verbose_name='لون التمييز (داكن)')),
                ('dark_color_background', models.CharField(default='#08121b', max_length=7, validators=[catalog.models._validate_hex_color], verbose_name='لون الخلفية (داكن)')),
                ('dark_color_surface', models.CharField(default='#0c1927', max_length=7, validators=[catalog.models._validate_hex_color], verbose_name='لون السطح (داكن)')),
                ('contact_cooldown_seconds', models.PositiveIntegerField(default=600, help_text='الحد الأدنى للفاصل الزمني بين رسائل التواصل (بالثواني)', verbose_name='فترة التبريد بين الرسائل (ثانية)')),
                ('contact_daily_limit', models.PositiveIntegerField(default=5, help_text='الحد اليومي الأقصى لرسائل التواصل لكل مستخدم', verbose_name='الحد اليومي للرسائل')),
                ('analytics_retention_days', models.PositiveIntegerField(default=90, help_text='عدد الأيام للاحتفاظ ببيانات التحليلات قبل حذفها', verbose_name='مدة الاحتفاظ ببيانات التحليلات (يوم)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'إعدادات المتجر',
                'verbose_name_plural': 'إعدادات المتجر',
                'db_table': 'store_settings',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(db_index=True, max_length=200, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(blank=True, default='', max_length=200, verbose_name='الاسم (إنجليزي)')),
                ('description_ar', models.TextField(blank=True, default='', verbose_name='الوصف (عربي)')),
                ('description_en', models.TextField(blank=True, default='', verbose_name='الوصف (إنجليزي)')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='المعرف')),
                ('price_sar', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر (ر.س)')),
                ('image', models.ImageField(upload_to='products/', verbose_name='الصورة الرئيسية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التعديل')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('headline_ar', models.CharField(blank=True, default='', max_length=300, verbose_name='العنوان الترويجي (عربي)')),
                ('headline_en', models.CharField(blank=True, default='', max_length=300, verbose_name='العنوان الترويجي (إنجليزي)')),
                ('subtitle_ar', models.CharField(blank=True, default='', max_length=500, verbose_name='العنوان الفرعي (عربي)')),
                ('subtitle_en', models.CharField(blank=True, default='', max_length=500, verbose_name='العنوان الفرعي (إنجليزي)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التعديل')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'منتج مميز',
                'verbose_name_plural': 'المنتجات المميزة',
                'db_table': 'featured_products',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='catalog.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'مفضلة',
                'verbose_name_plural': 'المفضلات',
                'db_table': 'favorites',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price_sar__gte', 0)), name='price_sar_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_user_product_favorite'),
        ),
    ]
