# Generated by Django 6.0.5 on 2026-05-23 09:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('img_url', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(db_index=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_edited', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_color_primary', models.CharField(default='#30669c', max_length=50)),
                ('light_color_secondary', models.CharField(default='#08121b', max_length=50)),
                ('light_color_accent', models.CharField(default='#e0801f', max_length=50)),
                ('light_color_background', models.CharField(default='#f6f1ee', max_length=50)),
                ('light_color_surface', models.CharField(default='#ffffff', max_length=50)),
                ('dark_color_primary', models.CharField(default='#39f2f9', max_length=50)),
                ('dark_color_secondary', models.CharField(default='#e0ebe7', max_length=50)),
                ('dark_color_accent', models.CharField(default='#e7994b', max_length=50)),
                ('dark_color_background', models.CharField(default='#08121b', max_length=50)),
                ('dark_color_surface', models.CharField(default='#0c1927', max_length=50)),
            ],
            options={
                'db_table': 'site_settings',
            },
        ),
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_edited', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.OneToOneField(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'db_table': 'featured_products',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
