# Generated by Django 6.0.6 on 2026-08-08 06:36

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to=catalog.models._unique_filename, verbose_name='الصورة الرئيسية'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=catalog.models._unique_filename, verbose_name='الصورة الرئيسية'),
        ),
    ]
